# Generated by Django 4.1.7 on 2023-03-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
