# Generated by Django 4.1.7 on 2023-03-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Product',
            field=models.ManyToManyField(blank=True, null=True, to='Home.product'),
        ),
    ]
