# Generated by Django 4.1.7 on 2023-03-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_cart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='profile_photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
