# Generated by Django 4.1.7 on 2023-03-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_rename_profile_photo_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='id',
        ),
    ]
