# Generated by Django 4.1.7 on 2023-03-16 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0009_cart_color_cart_quntity_cart_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
