# Generated by Django 4.1.7 on 2023-03-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_rename_cart_shopingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopingcart',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopingcart',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
